<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A text on designing, implementing, and reporting on Monte Carlo simulation studies">

<title>12&nbsp; Exploring and presenting simulation results – Designing Monte Carlo Simulations in R</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./074-building-good-vizualizations.html" rel="next">
<link href="./070-experimental-design.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9d6c9622e1db6294580745c4cacaf708.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="css/style.css">
<link rel="stylesheet" href="css/sidebar-toggle.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./060-multiple-scenarios.html">Systematic Simulations</a></li><li class="breadcrumb-item"><a href="./072-presentation-of-results.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exploring and presenting simulation results</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Designing Monte Carlo Simulations in R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/jepusto/Designing-Simulations-in-R" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Designing-Monte-Carlo-Simulations-in-R.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">An Introductory Look</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./001-introduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./003-programming-preliminaries.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Programming Preliminaries</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./005-initial-t-test-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">An initial simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Structure and Mechanics of a Simulation Study</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./010-Simulation-structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Structure of a simulation study</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./015-Case-study-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Case Study: Heteroskedastic ANOVA and Welch</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./020-Data-generating-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data-generating processes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./030-Estimation-procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estimation procedures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./035-running-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Running the Simulation Process</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./040-Performance-criteria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Performance Measures</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Systematic Simulations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./060-multiple-scenarios.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Simulating across multiple scenarios</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./070-experimental-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Designing multifactor simulations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./072-presentation-of-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exploring and presenting simulation results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./074-building-good-vizualizations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Building good visualizations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./075-special-topics-on-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Special Topics on Reporting Simulation Results</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./080-simulations-as-evidence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Simulations as evidence</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Computational Considerations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./100-file-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Organizing a simulation project</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./110-debugging-and-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Debugging and Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./120-parallel-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Parallel Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Complex Data Structures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./140-simulation-for-power-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Using simulation as a power calculator</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./150-potential-outcomes-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Simulation under the Potential Outcomes Framework</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./200-coding-tidbits.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Coding Reference</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#tabulation" id="toc-tabulation" class="nav-link active" data-scroll-target="#tabulation"><span class="header-section-number">12.1</span> Tabulation</a></li>
  <li><a href="#visualization" id="toc-visualization" class="nav-link" data-scroll-target="#visualization"><span class="header-section-number">12.2</span> Visualization</a></li>
  <li><a href="#modeling" id="toc-modeling" class="nav-link" data-scroll-target="#modeling"><span class="header-section-number">12.3</span> Modeling</a></li>
  <li><a href="#reporting" id="toc-reporting" class="nav-link" data-scroll-target="#reporting"><span class="header-section-number">12.4</span> Reporting</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/jepusto/Designing-Simulations-in-R/edit/main/072-presentation-of-results.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./060-multiple-scenarios.html">Systematic Simulations</a></li><li class="breadcrumb-item"><a href="./072-presentation-of-results.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exploring and presenting simulation results</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-presentation-of-results" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Exploring and presenting simulation results</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Once we have performance measures for each method examined for each scenario of our study’s design, the computationally challenging parts of a simulation study are complete, but several intellectually challenging tasks remain. The goal of a simulation study is to provide evidence to address a research question or questions, but performance measures (like numbers more generally) do not analyze themselves. Rather, they require interpretation, analysis, and communication in order to identify findings—that is, broad, potentially generalizable patterns of results—that are responsive the research questions. Good analysis aims to provide a clear understanding of how one or more of the simulation factors influence key performance measures of interest, the circumstances where a data analysis method works well or breaks down, and—in simulations that examine multiple methods—the conditions where one method performs better or worse than the alternatives.</p>
<p>In multi-factor simulations, the major challenge in analyzing simulation results is dealing with the multiplicity and dimensional nature of the results. For instance, in our cluster RCT simulation, we examined 270 different simulation scenarios, which vary along several factors. For each scenario, we calculated a whole suite of performance measures (bias, SE, RMSE, coverage, …), and we have these performance measures for each of the three estimation methods under consideration. We organized all these results as a data table with 810 rows (three rows per simulation scenario, with each row corresponding to a specific method) and one column per performance metric.</p>
<p>Navigating all of this can feel somewhat overwhelming. How do we understand trends in this complex, multi-factor data structure? Broadly, the answer is to think of the performance measures as outcomes of a designed experiment, so that we can bring to bear any and all of the data analysis techniques relevant to analyzing experimental designs involving real data.</p>
<p>In this chapter, we survey three main categories of analytic tools that can be used for exploring and presenting simulation results:</p>
<ol type="1">
<li>Tabulation</li>
<li>Visualization</li>
<li>Modeling</li>
</ol>
<p>For each category of tools, we describe the logic behind how it can be applied, provide high-level examples drawn from the literature and our own work, and discuss its strengths and limitations.</p>
<p>In this and subsequent chapters, we assume that you will be sharing the findings from your simulations with an audience beyond yourself. Depending on your circumstances, that might be a broad audience of researchers and data analysts, with whom you will communicate through a scholarly article in a peer-reviewed methodology journal; it might be colleagues who are evaluating your proposal for an empirical study, where the simulations serve to justify the data analysis protocol; it might be a small group of collaborators, who will use the simulations to make decisions about how to design a study; or it might be fellow students of statistics, interested to read a blog post that discusses how a particular model or method works. These contexts differ in the format and level of formality used to communicate findings. Still, in any of these contexts, you will probably need to create a written explanation of your findings, which summarizes what you found and presents evidence to support your assertions and interpretations. We close this chapter with a discussion about creating such write-ups and distilling your analysis into a set of exhibits for presentation.</p>
<section id="tabulation" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="tabulation"><span class="header-section-number">12.1</span> Tabulation</h2>
<p>Simulation study results are often presented in tables. A table might be fine if it involves only a few numbers and a few targeted comparisons or if it is important to report <em>exact</em> values for some quantities. However, simulations usually produce lots of numbers and require making many comparisons. For example, you might need to show the relative performance of several alternative estimators or the performance of your estimators under different conditions for the data-generating model. This usually means a lot of rows and a lot of dimensions. Tables can do two dimensions; when you try to cram more than that into a table, neither you nor your audience will be particularly well served. Furthermore, in simulation, exact values of performance measures are not usually of interest—in fact, we rarely have them due to Monte Carlo simulation error. Because of this, tables risk providing a false sense of uncertainty—unless you also report MCSEs, which would create further clutter. In general, we believe tables rarely make the take-aways of a simulation readily apparent. As a rule of thumb, if you are ever tempted into putting your table in landscape mode to get it to fit on the page, think again. It is usually more useful and insightful to present results in graphs <span class="citation" data-cites="gelman2002let">(<a href="references.html#ref-gelman2002let" role="doc-biblioref">Gelman et al. 2002</a>)</span>.</p>
<p>To illustrate, consider the following table of simulation results showing the false rejection rate, against an <span class="math inline">\(\alpha\)</span> of <span class="math inline">\(0.10\)</span>, for an estimator of an average treatment impact. We have two factors of interest, the treatment and control group sizes.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Rejection rates for a two-sample t-test assuming unequal variances</caption>
<thead>
<tr class="header">
<th style="text-align: right;">nT</th>
<th style="text-align: right;">nC</th>
<th style="text-align: right;">reject</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">31</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">500</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="even">
<td style="text-align: right;">500</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: right;">500</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td style="text-align: right;">500</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td style="text-align: right;">500</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This is the classic table you might see in a paper: the table is structured as groups of results indexed by one factor, with a second factor that varies within each group. The table makes clear that the rejection rates are often well above 10% and that the rates are all far too high when there are few treatment units. Because of the ordering of rows, it is somewhat more difficult to see how the number of control units impacts the rate, and understanding the joint relationship between number of treatment and number of control requires extra thinking.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-rejection-interaction-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rejection-interaction-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-rejection-interaction-plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rejection-interaction-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.1: Rejection rates for a two-sample t-test assuming unequal variances.
</figcaption>
</figure>
</div>
</div>
</div>
<p>By contrast, a plot of these exact same numbers can make trends much clearer. <a href="#fig-rejection-interaction-plot" class="quarto-xref">Figure&nbsp;<span>12.1</span></a> is an “interaction plot” showing the “interaction” of the factors nT and nC. This plot makes apparent that we only achieve something close to a valid test if both nC and nT are above 50. Even if nC is 500, the rejection rate is elevated if nT is only 10. When nT is 2, then increasing nC actually <em>increases</em> the rejection rate, meaning that larger samples make things worse. None of these trends were obvious from looking at the raw table results.</p>
<section id="sec-ITE-table-example" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="sec-ITE-table-example"><span class="header-section-number">12.1.1</span> Estimators of treatment variation</h3>
<p>Tables do serve some purposes. In general, tables are more useful for displaying high-level summaries of findings, such as average performance across a range of simulated scenarios, rather than for reporting raw results. For example, in ongoing work, Miratrix has been studying the performance of a suite of estimators designed to estimate individual treatment effects. To test which estimators perform better or worse than the others, we designed a series of scenarios where we varied the data-generating model by a variety of factors. For each scenario, we calculated the performance of each estimator relative to the median of all estimators considered. We can then ask, do some methods perform better than their peers on average across all scenarios considered?</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ITE-performance" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ITE-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.1: Relative performance measures of methods for estimating individual treatment effects
</figcaption>
<div aria-describedby="tbl-ITE-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">model</th>
<th style="text-align: right;">bias</th>
<th style="text-align: right;">se</th>
<th style="text-align: right;">rmse</th>
<th style="text-align: right;">sd_bias</th>
<th style="text-align: right;">sd_se</th>
<th style="text-align: right;">sd_rmse</th>
<th style="text-align: right;">R2</th>
<th style="text-align: right;">sd_R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BART S</td>
<td style="text-align: right;">-6</td>
<td style="text-align: right;">-28</td>
<td style="text-align: right;">-17</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">CF</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CF LC</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.19</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO R</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-21</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LASSO MCM EA</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-20</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO MOM DR</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">-21</td>
<td style="text-align: right;">-9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RF MOM DR</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-12</td>
<td style="text-align: right;">-8</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO T</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">-10</td>
<td style="text-align: right;">-6</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LASSO T INT</td>
<td style="text-align: right;">-4</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.28</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">LASSO MCM</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LASSO MOM IPW</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: right;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">ATE</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">-60</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RF T</td>
<td style="text-align: right;">-22</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">RF MOM IPW</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">0.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OLS S</td>
<td style="text-align: right;">-26</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0.31</td>
<td style="text-align: right;">0.22</td>
</tr>
<tr class="even">
<td style="text-align: left;">BART T</td>
<td style="text-align: right;">-38</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">54</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CDML</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">99</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: right;">0.20</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-ITE-performance" class="quarto-xref">Table&nbsp;<span>12.1</span></a> gives an answer to this question: we evaluate each method along four metrics: relative bias, relative se, relative rmse, and <span class="math inline">\(R^2\)</span>. To easily see which is good and which is bad, we averaged the performance measures across all scenarios and order the methods from highest average relative RMSE to lowest. Each cell of the table summarizes across 324 scenarios. The first several columns show relative performance. To calculate these values, for each method <span class="math inline">\(m\)</span>, performance metric <span class="math inline">\(Q\)</span>, and scenario <span class="math inline">\(s\)</span>, we calculated <span class="math inline">\(P_{ms} = Q_{ms} / median( Q_{ms} )\)</span>, and then averaged the <span class="math inline">\(P_{ms}\)</span> across the scenarios to get <span class="math inline">\(\bar{P}_m\)</span>. Each method also has an <span class="math inline">\(R^2_{ms}\)</span> value for each scenario; we simply take the average of these across all scenarios for the penultimate column. The standard deviation columns show the variation in performance across the full set of scenarios, providing some indication of how much the relative performance of a method changes from scenario to scenario. Representing this variation more explicitly might be better done with a visualization, as we explore shortly.</p>
<p>Overall, the table provides a nice, high-level summary of the results. It reports no less than four performance measures, one of which (the <span class="math inline">\(R^2\)</span>) is on a different scale than the others; this is hard to do in a single visualiztion. Despite these strengths, we still do not feel that the tables makes the results particularly visceral. A visualization can make trends jump out much more clearly.</p>
</section>
<section id="missing-data-and-causal-inference" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="missing-data-and-causal-inference"><span class="header-section-number">12.1.2</span> Missing data and causal inference</h3>
<p>For another example, <span class="citation" data-cites="zhou2015coarsened">Zhou et al. (<a href="references.html#ref-zhou2015coarsened" role="doc-biblioref">2015</a>)</span> examined the performance of a variety of methods for estimating causal effects in the presence of missing data. They present their simulation results in a series of tables. Their Table 2, for example, had four quadrants, each a distinct scenario. For example, the results for the scenario with misspecified outcome models and propensity score models looked like this:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">method</th>
<th style="text-align: right;">bias</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">rmse</th>
<th style="text-align: right;">mae</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naive</td>
<td style="text-align: right;">-10.00</td>
<td style="text-align: right;">1.56</td>
<td style="text-align: right;">10.12</td>
<td style="text-align: right;">9.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">RG</td>
<td style="text-align: right;">-0.77</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">1.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IPW</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">10.38</td>
<td style="text-align: right;">11.37</td>
<td style="text-align: right;">2.41</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stratified</td>
<td style="text-align: right;">-2.85</td>
<td style="text-align: right;">1.41</td>
<td style="text-align: right;">3.18</td>
<td style="text-align: right;">2.87</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIPW</td>
<td style="text-align: right;">-7.93</td>
<td style="text-align: right;">12.55</td>
<td style="text-align: right;">14.84</td>
<td style="text-align: right;">5.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIPW-S</td>
<td style="text-align: right;">-1.53</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">1.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AIPW-S1</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.12</td>
<td style="text-align: right;">1.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">AIPW-S1m</td>
<td style="text-align: right;">-1.59</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">1.63</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WR</td>
<td style="text-align: right;">-2.93</td>
<td style="text-align: right;">1.48</td>
<td style="text-align: right;">3.29</td>
<td style="text-align: right;">2.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">WR-S</td>
<td style="text-align: right;">-1.53</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">2.04</td>
<td style="text-align: right;">1.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WR-S1</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">1.59</td>
</tr>
<tr class="even">
<td style="text-align: left;">WR-S1m</td>
<td style="text-align: right;">-1.59</td>
<td style="text-align: right;">1.36</td>
<td style="text-align: right;">2.09</td>
<td style="text-align: right;">1.61</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TML</td>
<td style="text-align: right;">-37.60</td>
<td style="text-align: right;">332.08</td>
<td style="text-align: right;">334.03</td>
<td style="text-align: right;">4.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">TML-S</td>
<td style="text-align: right;">-1.53</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.08</td>
<td style="text-align: right;">1.59</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TML-S1</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">1.61</td>
</tr>
<tr class="even">
<td style="text-align: left;">TML-S1m</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">1.42</td>
<td style="text-align: right;">2.13</td>
<td style="text-align: right;">1.62</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Reading the table involves scanning across many methods, some of which are variants of the same core type. And this is only a quarter of the data—there are three other scenarios with results like these on the same table!</p>
<p>The table does provide all the information, but instead we can use a visualization. For our visualization we group methods by main type, and truncate outliers to put more focus on central tendencies. Below we plot the full Table 2 in this way, as one example. Our table corresponds to the second row in the plot; the other rows are the tables not shown (but see the paper itself). The outliers are circled to make their truncation clear.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="072-presentation-of-results_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Our plot makes the overall story more clear: the variants within method are generally the same, except for the TML estimator under the “neither” scenario. Many of the estimators have very similar performances to each other across the scenarios considered, but IPW approaches can be biased and more unstable.</p>
</section>
</section>
<section id="visualization" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="visualization"><span class="header-section-number">12.2</span> Visualization</h2>
<p>We see visualization as the primary technique for communicating simulation results. To illustrate some illustration principles, we next present a series of visualizations drawn from published simulations, each of which highlights some visualization design principles that we believe are broadly relevant and useful. In <a href="074-building-good-vizualizations.html" class="quarto-xref"><span>Chapter 13</span></a>, we present a more detailed look at the process of developing a polished visualization through iterative refinement of a series of plots.</p>
<section id="sec-ITE-graph-example" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="sec-ITE-graph-example"><span class="header-section-number">12.2.1</span> Relative performance of treatment effect estimators</h3>
<p>In <a href="#sec-ITE-table-example" class="quarto-xref"><span>Section 12.1.1</span></a>, we used a table to summarize the performance of a range of different methods of assessing individual-level variation in treatment effects. The table provided a compact high-level summary, but it could be improved by turning it into a visualization.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-MLIV-bar-chart" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-MLIV-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-MLIV-bar-chart-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MLIV-bar-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.2: Average relative performance of individual treatment effect estimators.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As a starting point, <a href="#fig-MLIV-bar-chart" class="quarto-xref">Figure&nbsp;<span>12.2</span></a> shows the same data as reported in the table, with the values of each performance measure depicted as bars (after rescaling <code>R2</code> by 100 to put it on a similar scale to the other measures). The Figure makes it easier to visually assess the extent to which the estimators follow consistent patterns in across the performance measures. However, this plot does not have any representation of the degree of variation across scenarios because the bars only represent the <em>average</em> performance across scenarios. We can elaborate this plot by using boxplots that summarize the distribution of performance measures across all scenarios examined.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-MLIV-box-chart" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-MLIV-box-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-MLIV-box-chart-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MLIV-box-chart-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.3: Relative performance of individual treatment effect estimators across all simulation scenarios.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The simulation evaluated performance across 324 distinct scenarios, and <a href="#fig-MLIV-box-chart" class="quarto-xref">Figure&nbsp;<span>12.3</span></a> shows the range of relative performances for each estimator across all of them. Using boxplots instead of bars highlights how much the relative performance can change from scenario to scenario. Just as in <a href="#tbl-ITE-performance" class="quarto-xref">Table&nbsp;<span>12.1</span></a> and <a href="#fig-MLIV-bar-chart" class="quarto-xref">Figure&nbsp;<span>12.2</span></a>, we order the methods from highest average RMSE to lowest. We use little circles to represent the average performance across all the simulations as little circles (these would correspond to the bars in <a href="#fig-MLIV-bar-chart" class="quarto-xref">Figure&nbsp;<span>12.2</span></a>). We truncate extreme values to make the plot more readable and bring focus to central tendencies. The x-axis is on a log scale, selected to navigate long tails and highlight relative performances. The log scaling also makes the scale of improved performance (less than x1) similar to worse performance (above x1).</p>
<p><a href="#fig-MLIV-box-chart" class="quarto-xref">Figure&nbsp;<span>12.3</span></a> depicts three different performance measures in a single plot. We dropped <span class="math inline">\(R^2\)</span> for this plot because the <span class="math inline">\(R^2\)</span> measure was in percentage points, and, due to estimation uncertainty, included negative values; this was not compatible with the log scaling.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> We have lost something in order to gain something. Ultimately, which plot is best is a matter of aesthetic judgement. Pick your plot based on whether it is clearly communicating the message you are trying to get across.</p>
</section>
<section id="sec-LRR-bias" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="sec-LRR-bias"><span class="header-section-number">12.2.2</span> Bias of log response ratios with auto-correlated data</h3>
<p><span class="citation" data-cites="Chen2024multilevel">Chen and Pustejovsky (<a href="references.html#ref-Chen2024multilevel" role="doc-biblioref">2024</a>)</span> examined the performance of a variety of effect size estimators used for quantifying treatment effects in single-case designs (SCDs), which are repeated measures designs that involve measuring an outcome variable on a single individual both before and after the introduction of a treatment. Typical SCDs involve quite short time series with closely spaced repeated measurements, so there is concern about whether auto-correlation in the outcome measurements affects estimation of effect sizes. <span class="citation" data-cites="Chen2024multilevel">Chen and Pustejovsky (<a href="references.html#ref-Chen2024multilevel" role="doc-biblioref">2024</a>)</span> reported some small simulations that examined the bias of different effect size estimators, including the log response ratio, under a data-generating process involving Poisson-distributed outcomes with a first-order auto-regression structure.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-LRR-bias" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-LRR-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-LRR-bias-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-LRR-bias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.4: Bias of the LRR1 estimator of the log response ratio under a Poisson AR(1) model with baseline mean of <span class="math inline">\(\mu_A = 10\)</span>, for varying log response ratio parameters, auto-correlation, and series length.
</figcaption>
</figure>
</div>
</div>
</div>
<p>One of the most common visualizations of simulation results is simply a line chart showing how a performance metric changes in response to some factor of interest.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Following the same construction as Figure 1 of <span class="citation" data-cites="Chen2024multilevel">Chen and Pustejovsky (<a href="references.html#ref-Chen2024multilevel" role="doc-biblioref">2024</a>)</span>, <a href="#fig-LRR-bias" class="quarto-xref">Figure&nbsp;<span>12.4</span></a> uses a simple line chart to depict how bias of the LRR1 effect size estimator is affected by the magnitude of the underlying parameter (on the horizontal axis) and the degree of auto-correlation, with varying levels of auto-correlation represented with different colors and different styles of line. We use multiple plots of a similar form to represent patterns across different numbers of data series lengths, from <span class="math inline">\(n = 5\)</span> to <span class="math inline">\(n = 15\)</span> measurements per phase. Figures such as <a href="#fig-LRR-bias" class="quarto-xref">Figure&nbsp;<span>12.4</span></a> clearly show how the bias is affected by the degree of auto-correlation, with larger positive auto-correlation amplifying the bias of the estimator. We also see that the bias is dampened as the series length increases.</p>
</section>
<section id="sec-biserial-correlation-visualization" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="sec-biserial-correlation-visualization"><span class="header-section-number">12.2.3</span> Biserial correlation estimation</h3>
<p>An extreme groups design is a clever way to evaluate the association between two variables when one of the variables is difficult or expensive to measure. It involves measuring one variable, <span class="math inline">\(X\)</span>, on a sample of participants but measuring the other variable, <span class="math inline">\(Y\)</span>, only for the subset of participants who have <span class="math inline">\(X\)</span> scores in the highest or lowest part of the distribution. The highest and lowest groups are defined based on some cut-off percentiles, which might be based on either the sample distribution or the population distribution of <span class="math inline">\(X\)</span>. The correlation between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> can be recovered by computing the biserial correlation coefficient between <span class="math inline">\(Y\)</span> and an indicator for whether the participant is in the highest or lowest part of the distribution.</p>
<p><span class="citation" data-cites="pustejovsky2014converting">Pustejovsky (<a href="references.html#ref-pustejovsky2014converting" role="doc-biblioref">2014</a>)</span> used simulation to examine the bias of biserial correlation estimates under the extreme groups design. This simulation was a full factorial design with four manipulated factors, including the true correlation for a range of values, cut-off type, cut-off percentile, and sample size. <a href="#fig-biserial-correlation" class="quarto-xref">Figure&nbsp;<span>12.5</span></a> reproduces a visualization of the bias of the biserial correlation estimator examined in <span class="citation" data-cites="pustejovsky2014converting">Pustejovsky (<a href="references.html#ref-pustejovsky2014converting" role="doc-biblioref">2014</a>)</span>. The correlation parameter, with 96 levels, runs along the horizontal axis and shows a smoothly varying bias curve. We use line type to represent the sample size, which makes it apparent that the bias shrinks as sample size increases. Finally, facetted plots are used to represent the remaining factors of cut-off type and cut-off percentile. All of the factors—and thousands of distinct simulation scenarios—are visible in a single plot.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-biserial-correlation" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-biserial-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-biserial-correlation-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-biserial-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.5: Bias of the biserial correlation estimate in an extreme groups design, for varying sample sizes, cut-off thresholds, and cut-off types. Source: Pustejovsky (2014).
</figcaption>
</figure>
</div>
</div>
</div>
<p>To make <a href="#fig-biserial-correlation" class="quarto-xref">Figure&nbsp;<span>12.5</span></a>, we smoothed the lines with respect to the correlation parameter <span class="math inline">\((\rho)\)</span> using locally weighted linear regressions (i.e., LOESS smoothing). Smoothing is a nice tool for taking some of the Monte Carlo error out of a figure to more directly represent overall trends.</p>
<p>This style of visualization, consisting of a grid of small plots, is called “many small multiples” and is beloved by Edward Tufte, who has written extensively on best practices for information design <span class="citation" data-cites="tufte1983visual">(see, for example, <a href="references.html#ref-tufte1983visual" role="doc-biblioref">Tufte and Graves-Morris 1983</a>)</span>. Tufte likes many small multiples, in part, because the technique can be used to display many different variables in a single plot: here, our facets are organized by two (<code>p1</code> and the cut-off approach), and the plot within each facet represents three (the outcome of bias, <span class="math inline">\(\rho\)</span> on the x-axis, and <span class="math inline">\(n\)</span> with line type). In this four-factor design, the small multiple plot lets us fully represent a performance measure across all combinations of the factors.</p>
</section>
<section id="sec-CRVE-F-tests" class="level3" data-number="12.2.4">
<h3 data-number="12.2.4" class="anchored" data-anchor-id="sec-CRVE-F-tests"><span class="header-section-number">12.2.4</span> Robust Hypothesis Testing for Meta-regression</h3>
<p></p>
<p>In our next example, drawn from <span class="citation" data-cites="tipton2015small">Tipton and Pustejovsky (<a href="references.html#ref-tipton2015small" role="doc-biblioref">2015</a>)</span>, we explore Type-I error rates of small-sample corrected F-tests based on cluster-robust variance estimation in meta-regression models. The simulation aimed to compare 5 different small-sample corrections for hypothesis tests involving multiple constraints (i.e., multiple regression coefficients). This was another complex experimental design, which involved varying several factors:</p>
<ul>
<li>sample size (<span class="math inline">\(m\)</span>)</li>
<li>dimension of the hypothesis (<span class="math inline">\(q\)</span>)</li>
<li>covariates tested</li>
<li>degree of model mis-specification</li>
</ul>
<p>The Type I error rates of all five tests are depicted in <a href="#fig-CRVE-Ftests" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-CRVE-Ftests" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-CRVE-Ftests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-CRVE-Ftests-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-CRVE-Ftests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.6: Type-I error rates of selected hypothesis testing procedures for meta-regression models with cluster-robust variance estimation. Source: Tipton and Pustejovsky (2015).
</figcaption>
</figure>
</div>
</div>
</div>
<p>As in the previous example, <a href="#fig-CRVE-Ftests" class="quarto-xref">Figure&nbsp;<span>12.6</span></a> uses small multiples to show variation in the results across two simulation factors (sample size <span class="math inline">\(m\)</span> and hypothesis dimension <span class="math inline">\(q\)</span>). The <span class="math inline">\(x\)</span>-axis shows each of the five hypothesis testing procedures under comparison. The boxplots depict the <em>distribution</em> of the performance measure across the remaining factors in the design; Each box shows the range, inter-quartile range, and median of the Type-I error rates for a given test procedure across the various covariates tested and different degrees of model misspecification. For reference, we add a solid line at the target .05 rejection rate and a dashed line at the upper bound of a 90% confidence interval for an estimate with a true rejection rate of .05. The spread of the boxes shows how some methods are more or less vulnerable to different types of misspecification. Some estimators (e.g., <span class="math inline">\(T^2_A\)</span>) are clearly hyper-conservative, with very low rejection rates. Other methods (e.g., EDF), have a range of very high rejection rates when <span class="math inline">\(m = 10\)</span> but converge to the target level as the sample size incrases. For these tests, the degree of rejection rate depends on the degree of model mis-specification and the particular covariates tested (i.e., the remaining factors captured in the boxes).</p>
</section>
<section id="sec-coverage-heat-maps" class="level3" data-number="12.2.5">
<h3 data-number="12.2.5" class="anchored" data-anchor-id="sec-coverage-heat-maps"><span class="header-section-number">12.2.5</span> Heat maps of coverage</h3>
<p>For data with many levels of two different factors, one useful visualization technique is a heat map. For instance, <span class="citation" data-cites="Brown1977estimation">Brown et al. (<a href="references.html#ref-Brown1977estimation" role="doc-biblioref">1977</a>)</span> studied methods of estimating the features of a binary (on/off) process occurring over time when that process is observed using momentary time sampling (MTS). MTS involves recording whether a process is on or off at specific moments that are evenly spaced over time. Under certain assumptions, the underlying process can be described by two parameters: prevalence, or the overall proportion of time that the process in on, and incidence, or the rate at which the process cycles between states. <span class="citation" data-cites="Brown1977estimation">Brown et al. (<a href="references.html#ref-Brown1977estimation" role="doc-biblioref">1977</a>)</span> proposed maximum likelihood estimators (MLEs) for the prevalence and incidence parameters based on a sequence of MTS data.</p>
<p>Using simulation, Pustejovsky studied the performance of the maximum likelihood estimator and suggested an alternative of using penalized maximum likelihood and bootstrap confidence intervals. The simulation design involved varying three factors: prevalence, incidence, and the length of the MTS sequence. Because the prevalence parameter can take any value between 0 and 1 and the incidence parameter can take any positive value, we examined a large number of levels of each of these factors, with 10 levels for prevalence and 10 levels for incidence, plus 12 levels for sample size. We limited the levels of prevalence to run from 0.05 to 0.50 because the estimators work symmetrically for prevalence values above and below 0.50.</p>
<p><a href="#fig-MTS-coverage" class="quarto-xref">Figure&nbsp;<span>12.7</span></a> shows the coverage of parametric bootstrap confidence intervals for the prevalence parameter. The plot shows the combinations of prevalence and incidence as a grid for each sample size level. We break coverage into ranges of interest, with green being “good” (near 95%), yellow being “close” (92.5% or above), blue and purple being conservative (above 95%) coverage, and red being poor (below 92.5%). For this kind of plotting to work effectively, we need the MCSE to be small enough that the structure of the coverage levels are apparent. The figure consists of two panels, with the left panel showing results for smaller sample sizes and the right panel showing results for the larger sample sizes. We <em>wrap</em> the small multiples by sample size, so that the overall figure design runs from smallest sample size on the upper left to largest sample size on the lower right. Wrappings can be useful if you have many levels of a single factor, although it does not take advantage of the two-dimensional layout of the grid (such as we saw with examples <a href="#sec-biserial-correlation-visualization" class="quarto-xref"><span>Section 12.2.3</span></a> and <a href="#sec-CRVE-F-tests" class="quarto-xref"><span>Section 12.2.4</span></a>). Within each panel, results for the original MLE and the penalized MLE are arranged size-by-side to facilitate comparison between methods.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-MTS-coverage" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-MTS-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-MTS-coverage-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MTS-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.7: Coverage of bootstrap confidence intervals for maximum likelihood estimator and penalized maximum likelihood estimator of prevalence based on momentary time sampling data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Looking across sample sizes in <a href="#fig-MTS-coverage" class="quarto-xref">Figure&nbsp;<span>12.7</span></a>, we see clear trends, where the coverage of both estimators degrades for low incidence rates. The field of green in the right column of each panel indicates that the penalized MLE works well across a large part of the parameter space. The left columns of each panel have less green, indicating that the original MLE has worse coverage Comparing left and right, the improvement of the penalized MLE over the original MLE is evident.</p>
</section>
<section id="sec-head-to-head-accuracy" class="level3" data-number="12.2.6">
<h3 data-number="12.2.6" class="anchored" data-anchor-id="sec-head-to-head-accuracy"><span class="header-section-number">12.2.6</span> Head-to-head comparison of accuracy</h3>
<p>Comparing the performance of different estimation methods is often a central focus of simulation studies, and so it is often important to construct figures to facilitate such comparisons. In Examples <a href="#sec-ITE-graph-example" class="quarto-xref"><span>Section 12.2.1</span></a>, <a href="#sec-CRVE-F-tests" class="quarto-xref"><span>Section 12.2.4</span></a>, and <a href="#sec-coverage-heat-maps" class="quarto-xref"><span>Section 12.2.5</span></a>, we saw figures designed to allow side-by-side comparisons of different estimators. A drawback of the figures presented in Examples <a href="#sec-ITE-graph-example" class="quarto-xref"><span>Section 12.2.1</span></a> and <a href="#sec-CRVE-F-tests" class="quarto-xref"><span>Section 12.2.4</span></a> is that they aggregate the results over multiple scenarios, which makes it difficult to know whether one estimator out-performs <em>always</em> outperforms another or if it is worse under some conditions but better under others. For instance, in <a href="#fig-CRVE-Ftests" class="quarto-xref">Figure&nbsp;<span>12.6</span></a>, does the <span class="math inline">\(T_Z^2\)</span> test always have lower Type I error than the EDF test? Or are there conditions where EDF is more conservative? There is no way to tell from the results presented because the box-plots are summarizing over multiple scenarios.</p>
<p>Several other plotting techniques can be useful for presenting head-to-head comparisons of performance. To illustrate these, we use data from <span class="citation" data-cites="chen2025adapting">Chen and Pustejovsky (<a href="references.html#ref-chen2025adapting" role="doc-biblioref">2025</a>)</span>, who studied the performance of a variety of estimators for average effect size in meta-analyses involving dependent effect sizes and selective reporting bias. Each estimator examined had two versions, involving either a univariate working model (where all effect sizes were treated as independent) or a multivariate working model (that treats effect sizes drawn from the same study as correlated). Thus, one of several questions of interest in this simulation was about the degree to which using a multivariate working model led to improved accuracy of an estimator.</p>
<p><a href="#fig-head-to-head-RMSE" class="quarto-xref">Figure&nbsp;<span>12.8</span></a> is adapted from Figure 5b of <span class="citation" data-cites="chen2025adapting">Chen and Pustejovsky (<a href="references.html#ref-chen2025adapting" role="doc-biblioref">2025</a>)</span> and depicts a subset of the results from our full simulation, focusing on the RMSE of the univariate and multivariate versions of the estimators. Each panel corresponds to a separate estimator. Within a panel, the horizontal and vertical axes correspond to the RMSE of the univariate and multivariate estimator, respectively. Each point represents the performance of the estimators under a single simulation scenario; the color of the point corresponds to the selection weight used to generate the data. A dashed line at <span class="math inline">\(y = x\)</span> indicates the point where both versions have equal accuracy.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-head-to-head-RMSE" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-head-to-head-RMSE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-head-to-head-RMSE-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-head-to-head-RMSE-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.8: Comparison of the RMSE of multivariate working models versus the RMSE of univariate counterparts under a one-step selection process for <span class="math inline">\(k = 30\)</span> studies and <span class="math inline">\(\bar{\rho} = 0.4\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The head-to-head layout of <a href="#fig-head-to-head-RMSE" class="quarto-xref">Figure&nbsp;<span>12.8</span></a> makes it easy to see that the multivariate versions of each estimator tend to have slightly lower RMSE than their univariate counterparts and that this is true not only on average, but also across the conditions depicted in the figure. Furthermore, the performance advantage of the multivariate estimators seems to be approximately multiplicative: using the multivariate version instead of the univariate version reduces RMSE by close to a constant percentage. However, the figure is still limited to a subset of conditions because depicting every sample size and every setting for <span class="math inline">\(\bar\rho\)</span> would make it too noisy to see these trends. A further drawback of this layout is that it is difficult to see the relationship for scenarios where both versions of an estimator have relatively low RMSE; instead, the eye tends to be drawn to outliers (such as the red dots with the highest values of RMSE).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-RMSE-ratio" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-RMSE-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-RMSE-ratio-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-RMSE-ratio-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.9: Ratio of RMSE of multivariate working models to the RMSE of univariate counterparts under a one-step selection process for <span class="math inline">\(k = 30\)</span> studies and <span class="math inline">\(\bar{\rho} = 0.4\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-RMSE-ratio" class="quarto-xref">Figure&nbsp;<span>12.9</span></a> illustrates another way to depict head-to-head comparisons of the accuracy of two estimators. Rather than plotting one versus the other, we have calculated and plotted the ratio of the RMSE for the multivariate estimator relative to the RMSE of the univariate version. Thus, RMSE ratios less than one correspond to scenarios where the multivariate version is more accurate. Each point still corresponds to a unique scenario, and the number of points in each panel is identical to the number in <a href="#fig-head-to-head-RMSE" class="quarto-xref">Figure&nbsp;<span>12.8</span></a>. This representation makes it much easier to see how relative accuracy is affected by the selection weight; for instance, the advantage of the multivariate versions of the PET/PEESE, EK, and WILS estimators tend to weaken for smaller selection weights. Further, plotting at the RMSE ratio has freed up one dimension of the graph, which could allow us to represent one further dimension of the simulation design in the figure.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> The main drawback of plotting the ratio is that the figure does not provide information about the absolute magnitude of the RMSE.</p>
</section>
</section>
<section id="modeling" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="modeling"><span class="header-section-number">12.3</span> Modeling</h2>
<p>Simulations are designed experiments, often with a full factorial structure. The results are datasets in their own right, just as if we had collected data in the wild. We can therefore leverage classical techniques for analyzing full factorial experiments. For example, regressing a performance measure against our factor levels provides a quantitative description of how the different levels influence performance, holding the other factors constant. This type of regression has been described as a “meta-regression” <span class="citation" data-cites="kleijnen1981regression friedman1988metamodel gilbert2024multilevel">(<a href="references.html#ref-kleijnen1981regression" role="doc-biblioref">Kleijnen 1981</a>; <a href="references.html#ref-friedman1988metamodel" role="doc-biblioref">Friedman and Pressman 1988</a>; <a href="references.html#ref-gilbert2024multilevel" role="doc-biblioref">Gilbert and Miratrix 2024</a>)</span> because it involves a regression model where the response variable is itself a summary estimate of some performance measure.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> The technique also has ties to meta-analysis <span class="citation" data-cites="borenstein2021introduction">(see, e.g., <a href="references.html#ref-borenstein2021introduction" role="doc-biblioref">Borenstein et al. 2021</a>)</span>, which involves summarizing and examining trends across sets of empirical findings from different studies.</p>
<p>One useful summary of a meta-regression model is an analysis of variance (ANOVA) table that decomposes the variation in the performance measure into different sources. In the language of a full factorial experiment, the ANOVA table typically includes both “main effects” and “interaction effects.” Main effects characterize the extent to which a particular factor systematically influences performance, when averaging across all other factors in the design. By aggregating over other factors, main effects will capture the broadest possible patterns; if we see a trend when we average over all the other varying factors, then we can infer that the finding is relevant across the many different simulation contexts explored, rather than being an idiosyncratic feature of a specific and narrow context. Interaction effects characterize the degree to which patterns or trends observed in one factor are themselves variable, changing depending on the level of another factor. Interactions provide an indication of how the influence of a particular factor might matter more or less, depending on other aspects of the context.</p>
<p>In simulations that involve comparing multiple methods, we might approach meta-regression models in one of two ways. One possibility would be to include the method itself as a factor in the meta-regression. With this approach, the estimated main effect for each method will describe the extent to which a method is higher or lower than the baseline method, on average across all the simulation scenarios. The main effects of the simulation factors will tell us the extent to which each factor influences the performance measure on average across all the methods considered. For instance, we might expect that the true standard error goes down as sample size increases, following a consistent pattern across all methods. With this approach, we would need to examine interactions between method and the other factors, to see how the methods vary in the extent to which they are influenced by the simulation scenario.</p>
<p>Another approach would be to use separate meta-regression models for each of the multiple methods. This approach makes it somewhat easier to understand the influence of the simulation design factors on the performance of each method. Using separate meta-regressions, we might find that a certain factor has a very strong influence on the bias and RMSE of one particular method, whereas it has little or no influence on the performance of a different method. The challenge with this approach is that it becomes more difficult to identify patterns that hold across all methods or to draw comparisons across different methods.</p>
<section id="comparing-methods-for-cross-classified-data" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="comparing-methods-for-cross-classified-data"><span class="header-section-number">12.3.1</span> Comparing methods for cross-classified data</h3>
<p><span class="citation" data-cites="lee2023comparing">Lee and Pustejovsky (<a href="references.html#ref-lee2023comparing" role="doc-biblioref">2023</a>)</span> were interested in evaluating how different modeling approaches perform when analyzing cross-classified data structures in which students were nested both in schools and in neighborhoods. To do this, we conducted a multi-factor simulation to compare three methods: a cross-classified random effects model (CCREM), a simple, ordinary least squares model with two-way cluster-robust variance estimation (CRVE), and a two-way fixed effects model, also with CRVE. The simulation was complex, involving several factors including the magnitude of effect <span class="math inline">\((r)\)</span>, the number of schools <span class="math inline">\((H)\)</span>, the number of students per school <span class="math inline">\((J)\)</span>, a school-level intra-unit correlation coefficient (IUCC), and whether the data-generating process involved violations of certain assumptions of the CCREM.</p>
<p>To understand which factors had the most influence on the bias of the three methods, we used an ANOVA model. We were interested in understanding the factors that influenced bias both when all assumptions of the CCREM held and when each of several assumptions was violated. We therefore computed four separate ANOVA summaries—one for each scenario where all assumptions were met, where homoskedasticity was violated, where exogeneity was violated, and where there were unmodeled random slopes. This approach let us understand which of the remaining factors were important influences on the parameter bias of the methods examined.</p>
<p>The supplementary materials of <span class="citation" data-cites="lee2023comparing">Lee and Pustejovsky (<a href="references.html#ref-lee2023comparing" role="doc-biblioref">2023</a>)</span> (Table S5.2, available at https://osf.io/hy73g and reproduced as <a href="#tbl-ccrem-ANOVA" class="quarto-xref">Table&nbsp;<span>12.2</span></a>) reported the results of these four ANOVA models, with columns corresponding to each of the four assumption scenarios and rows corresponding to factors manipulated within that context. The magnitude of the effects is expressed as partial <span class="math inline">\(\eta^2\)</span> effect sizes; Small, medium, and large effects are marked to make them jump out to the eye.</p>
<div class="cell" data-layout-align="center">
<div id="tbl-ccrem-ANOVA" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-layout-align="center">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ccrem-ANOVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12.2: Partial <span class="math inline">\(\eta^2\)</span> values from ANOVA of parameter bias in a simulation of cross-classified data
</figcaption>
<div aria-describedby="tbl-ccrem-ANOVA-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 16%">
<col style="width: 26%">
<col style="width: 20%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Assumptions Met</th>
<th style="text-align: left;">Homoskedasticity Violated</th>
<th style="text-align: left;">Exogeneity Violated</th>
<th style="text-align: left;">Random Slopes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Method</td>
<td style="text-align: left;">0.000</td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.995 L</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Effect Size (r)</td>
<td style="text-align: left;">0.131 M</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.020 S</td>
<td style="text-align: left;">0.142 L</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of Schools (H)</td>
<td style="text-align: left;">0.014 S</td>
<td style="text-align: left;">0.113 M</td>
<td style="text-align: left;">0.188 L</td>
<td style="text-align: left;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">Students per School (J)</td>
<td style="text-align: left;">0.016 S</td>
<td style="text-align: left;">0.016 S</td>
<td style="text-align: left;">0.747 L</td>
<td style="text-align: left;">0.110 M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IUCC</td>
<td style="text-align: left;">0.007</td>
<td style="text-align: left;">0.007</td>
<td style="text-align: left;">0.033 S</td>
<td style="text-align: left;">0.073 M</td>
</tr>
<tr class="even">
<td style="text-align: left;">method × r</td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.007</td>
<td style="text-align: left;">0.012 S</td>
</tr>
<tr class="odd">
<td style="text-align: left;">method × H</td>
<td style="text-align: left;">0.004</td>
<td style="text-align: left;">0.002</td>
<td style="text-align: left;">0.157 L</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">method × J</td>
<td style="text-align: left;">0.002</td>
<td style="text-align: left;">0.000</td>
<td style="text-align: left;">0.878 L</td>
<td style="text-align: left;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">method × IUCC</td>
<td style="text-align: left;">0.012 S</td>
<td style="text-align: left;">0.003</td>
<td style="text-align: left;">0.037 S</td>
<td style="text-align: left;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">r × H</td>
<td style="text-align: left;">0.103 M</td>
<td style="text-align: left;">0.010</td>
<td style="text-align: left;">0.059 S</td>
<td style="text-align: left;">0.377 L</td>
</tr>
<tr class="odd">
<td style="text-align: left;">r × J</td>
<td style="text-align: left;">0.006</td>
<td style="text-align: left;">0.024 S</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.051 S</td>
</tr>
<tr class="even">
<td style="text-align: left;">r × IUCC</td>
<td style="text-align: left;">0.065 M</td>
<td style="text-align: left;">0.025 S</td>
<td style="text-align: left;">0.084 M</td>
<td style="text-align: left;">0.136 M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H × J</td>
<td style="text-align: left;">0.002</td>
<td style="text-align: left;">0.014 S</td>
<td style="text-align: left;">0.062 M</td>
<td style="text-align: left;">0.105 M</td>
</tr>
<tr class="even">
<td style="text-align: left;">H × IUCC</td>
<td style="text-align: left;">0.024 S</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.034 S</td>
<td style="text-align: left;">0.137 M</td>
</tr>
<tr class="odd">
<td style="text-align: left;">J × IUCC</td>
<td style="text-align: left;">0.004</td>
<td style="text-align: left;">0.088 M</td>
<td style="text-align: left;">0.013 S</td>
<td style="text-align: left;">0.029 S</td>
</tr>
</tbody>
</table>
<p><strong>Note:</strong> (S)mall = .01, (M)edium = .06, (L)arge = .14</p>
</div>
</div>
</figure>
</div>
</div>
<p>In the second column of <a href="#tbl-ccrem-ANOVA" class="quarto-xref">Table&nbsp;<span>12.2</span></a>, we see that when model assumptions are met or only homoscedasticity is violated, the choice of method (CCREM, OLS-CRVE, FE-CRVE) has almost no impact on parameter bias (<span class="math inline">\(\eta^2 = 0.000\)</span> to 0.006). However, under an exogeneity violation, method choice has a large effect (<span class="math inline">\(\eta^2 = 0.995\)</span>), indicating that some methods (e.g., OLS-CRVE) have much more bias than others. Other factors such as the effect size of the parameter and the number of schools can also show moderate-to-large impacts on bias in several conditions. <a href="#tbl-ccrem-ANOVA" class="quarto-xref">Table&nbsp;<span>12.2</span></a> also shows how an interaction between simulation factors can matter. For example, interactions between method and number of schools, or students per school, can really impact bias under the Exogeniety Violated condition; this means the different methods respond differently as sample size changes. Overall, the ANOVA exercise was a useful preliminary step in our analysis because it provided a succinct summary of how some aspects of the simulation’s design matter more and some matter less. We used the results to inform the design of visualizations for illustrating key findings from the simulation.</p>
</section>
<section id="biserial-correlations-revisited" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="biserial-correlations-revisited"><span class="header-section-number">12.3.2</span> Biserial correlations, revisited</h3>
<p>In the biserial correlation example described in <a href="#sec-biserial-correlation-visualization" class="quarto-xref"><span>Section 12.2.3</span></a>, we saw that bias can change notably across scenarios considered, and that several factors appear to be driving these changes. These factors also seem to have complex interactions: note how when p1 = 0.5, we get larger dips than when p1 = 1/8. <a href="#fig-biserial-correlation" class="quarto-xref">Figure&nbsp;<span>12.5</span></a> gives a sense of the complex combination of factors that influence bias and also suggests some possibilities for further analysis. In particular, the figure suggests that the bias grows smaller as the sample size increases. We used this observation to develop a model in which the bias is inversely proportional to the sample size, as in <span class="math display">\[
B_{pqrs} = \beta_{pqr} \times \frac{1}{N_s} + e_{pqrs},
\]</span> where <span class="math inline">\(B_{pqrs}\)</span> is the estimated bias for cut-off level <span class="math inline">\(p\)</span>, cut-off type <span class="math inline">\(q\)</span>, true correlation level <span class="math inline">\(r\)</span>, and sample size level <span class="math inline">\(s\)</span>, <span class="math inline">\(N_s\)</span> is the actual value of sample size level <span class="math inline">\(s\)</span>, and <span class="math inline">\(e_{pqrs}\)</span> is an error capturing the Monte Carlo uncertainty in the bias estimate.</p>
<p>Because the model reduces the dimension of the simulation’s design, relying on it allow us to simplify further analysis and presentation of the simulation results. For instance, we used the model to motivate construction of <a href="#fig-biserial-beta-summary" class="quarto-xref">Figure&nbsp;<span>12.10</span></a>, which shows how <span class="math inline">\(\beta_{pqr}\)</span> varies for different cut-off values, cut-off types, and correlation parameters. The results presented are aggregated across the sample size factor because we have fully accounted for how it affects bias.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-biserial-beta-summary" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-biserial-beta-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="072-presentation-of-results_files/figure-html/fig-biserial-beta-summary-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-biserial-beta-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12.10: <span class="math inline">\(N\)</span> times the bias of the biserial correlation estimate in an extreme groups design as a function of <span class="math inline">\(\rho\)</span>, cut-off thresholds, and cut-off types.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="reporting" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="reporting"><span class="header-section-number">12.4</span> Reporting</h2>
<p>Just as with empirical data analysis, the analysis that you present in an outward-facing report will usually be only a summary of all of the analysis that you conduct to arrive at your findings. Typically, you will need to make many figures and tables, and potentially explore several different modeling techniques in order to identify the important patterns in a set of simulation results. You need to work through such analysis in order to develop a strong understanding of what is going on in a set of simulation results. You will then need to clarify the story by distilling your full analysis into a selection of figures, tables, and summaries that explain your findings while maintaining honesty and transparency. Some of the remainder will then become supplementary materials that contain further detail to both enrich your main narrative and demonstrate that you are not hiding anything.</p>
<p>When presenting results, it is important to not pummel readers with a deluge of tables, figures, and observations. Instead, strive to present summaries of results that clearly illustrate the main findings from the study—that is, the patterns and trends that most directly respond to the research questions—and also draw attention to any results that are unusual or anomalous. Often, an audience will be best served with a few well-chosen figures. In the text of a write-up, you might also include a few specific numerical comparisons. Do not include too many of these, and be sure that it is clear why the numerical comparisons you include are important.</p>
<p>Findings from a simulation study are by definition a simplified summary of a complex phenomenon. Alert readers will know this and will be cautiously attuned to (or outright skeptical about) details not represented in the final set of exhibits. To support transparency, you should also provide code for reproducing the entire simulation, along with data files containing the full detail of your simulation results. Sharing code allows any interested reader to rerun the simulation and conduct your analysis themselves or to rerun your simulation under different conditions. Sharing a data file of simulation results allows readers to verify or further probe the patterns that you identify in your write-up, to visualize or analyze results in novel ways, or to examine subsets of conditions that might be of particular interest.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-antonakis2021ignoring" class="csl-entry" role="listitem">
Antonakis, John, Nicolas Bastardoz, and Mikko Rönkkö. 2021. <span>“On Ignoring the Random Effects Assumption in Multilevel Models: Review, Critique, and Recommendations.”</span> <em>Organizational Research Methods</em> 24 (2): 443–83.
</div>
<div id="ref-borenstein2021introduction" class="csl-entry" role="listitem">
Borenstein, Michael, Larry V. Hedges, Julian P. T. Higgins, and Hannah R. Rothstein. 2021. <em>Introduction to Meta-Analysis</em>. 3rd ed. John Wiley &amp; Sons.
</div>
<div id="ref-Brown1977estimation" class="csl-entry" role="listitem">
Brown, M, H Solomon, and M A Stephens. 1977. <span>“Estimation of Parameters of Zero-One Processes by Interval Sampling.”</span> <em>Operations Research</em> 25 (3): 493–505.
</div>
<div id="ref-Chen2024multilevel" class="csl-entry" role="listitem">
Chen, Man, and James E. Pustejovsky. 2024. <span>“Multi-Level Meta-Analysis of Single-Case Experimental Designs Using Robust Variance Estimation.”</span> <em>Psychological Methods</em> 29 (3): 537–60. <a href="https://doi.org/10.1037/met0000510">https://doi.org/10.1037/met0000510</a>.
</div>
<div id="ref-chen2025adapting" class="csl-entry" role="listitem">
Chen, Man, and James E. Pustejovsky. 2025. <span>“Adapting Methods for Correcting Selective Reporting Bias in Meta-Analysis of Dependent Effect Sizes.”</span> <em>Psychological Methods</em>, ahead of print, June 9. <a href="https://doi.org/10.1037/met0000773">https://doi.org/10.1037/met0000773</a>.
</div>
<div id="ref-friedman1988metamodel" class="csl-entry" role="listitem">
Friedman, Linda Weiser, and Israel Pressman. 1988. <span>“The Metamodel in Simulation Analysis: Can It Be Trusted?”</span> <em>Journal of the Operational Research Society</em> 39 (10): 939–48.
</div>
<div id="ref-gelman2002let" class="csl-entry" role="listitem">
Gelman, Andrew, Cristian Pasarica, and Rahul Dodhia. 2002. <span>“Let’s Practice What We Preach: Turning Tables into Graphs.”</span> <em>The American Statistician</em> 56 (2): 121–30.
</div>
<div id="ref-gilbert2024multilevel" class="csl-entry" role="listitem">
Gilbert, Joshua, and Luke Miratrix. 2024. <span>“Multilevel Metamodels: A Novel Approach to Enhance Efficiency and Generalizability in Monte Carlo Simulation Studies.”</span> <em>arXiv Preprint arXiv:2401.07294</em>.
</div>
<div id="ref-kleijnen1981regression" class="csl-entry" role="listitem">
Kleijnen, Jack PC. 1981. <span>“Regression Analysis for Simulation Practitioners.”</span> <em>Journal of the Operational Research Society</em> 32 (1): 35–43.
</div>
<div id="ref-lee2023comparing" class="csl-entry" role="listitem">
Lee, Young Ri, and James E Pustejovsky. 2023. <span>“Comparing Random Effects Models, Ordinary Least Squares, or Fixed Effects with Cluster Robust Standard Errors for Cross-Classified Data.”</span> <em>Psychological Methods</em>.
</div>
<div id="ref-little2013praise" class="csl-entry" role="listitem">
Little, Roderick J. 2013. <span>“In Praise of Simplicity Not Mathematistry! Ten Simple Powerful Ideas for the Statistical Scientist.”</span> <em>Journal of the American Statistical Association</em> 108 (502): 359–69.
</div>
<div id="ref-patchwork" class="csl-entry" role="listitem">
Pedersen, Thomas Lin. 2024. <em>Patchwork: The Composer of Plots</em>. <a href="https://patchwork.data-imaginist.com">https://patchwork.data-imaginist.com</a>.
</div>
<div id="ref-pustejovsky2014converting" class="csl-entry" role="listitem">
Pustejovsky, James E. 2014. <span>“Converting from d to r to z When the Design Uses Extreme Groups, Dichotomization, or Experimental Control.”</span> <em>Psychological Methods</em> 19 (1): 92.
</div>
<div id="ref-tipton2015small" class="csl-entry" role="listitem">
Tipton, Elizabeth, and James E Pustejovsky. 2015. <span>“Small-Sample Adjustments for Tests of Moderators and Model Fit Using Robust Variance Estimation in Meta-Regression.”</span> <em>Journal of Educational and Behavioral Statistics</em> 40 (6): 604–34.
</div>
<div id="ref-tufte1983visual" class="csl-entry" role="listitem">
Tufte, Edward R, and Peter R Graves-Morris. 1983. <em>The Visual Display of Quantitative Information</em>. Graphics press Cheshire, CT.
</div>
<div id="ref-zhou2015coarsened" class="csl-entry" role="listitem">
Zhou, Jie, Zhiwei Zhang, Zhaohai Li, and Jun Zhang. 2015. <span>“Coarsened Propensity Scores and Hybrid Estimators for Missing Data and Causal Inference.”</span> <em>International Statistical Review</em> 83 (3): 449–71.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>To represent all four performance measures, we could create a separate plot of <span class="math inline">\(R^2\)</span> and add it to the right-hand side of <a href="#fig-MLIV-box-chart" class="quarto-xref">Figure&nbsp;<span>12.3</span></a>. The <code>patchwork</code> package <span class="citation" data-cites="patchwork">(<a href="references.html#ref-patchwork" role="doc-biblioref">Pedersen 2024</a>)</span> provides tools for creating composite plots such as this.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>In a discussion about the importance of simulation, <span class="citation" data-cites="little2013praise">Little (<a href="references.html#ref-little2013praise" role="doc-biblioref">2013</a>)</span> provides several further examples of this type of plot, including figures showing an RMSE and confidence interval coverage for four estimators of a regression coefficient when using a calibration procedure. <span class="citation" data-cites="antonakis2021ignoring">Antonakis et al. (<a href="references.html#ref-antonakis2021ignoring" role="doc-biblioref">2021</a>)</span> uses similar plots to report results from a simulation examining what happens when random effect assumptions are ignored in multilevel modeling.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><a href="#fig-RMSE-ratio" class="quarto-xref">Figure&nbsp;<span>12.9</span></a> uses color to represent different levels of the selection weight parameter, even though this is redundant with the horizontal axis of each panel. We have used this redundant mapping to emphasize the parallels with <a href="#fig-head-to-head-RMSE" class="quarto-xref">Figure&nbsp;<span>12.8</span></a>, even though it is not strictly necessary. We could instead add further results to the figure by using color to represent different levels of the <span class="math inline">\(\bar\rho\)</span> parameter.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Meta-regression can also be used to account for Monte Carlo uncertainty in some contexts, which can be especially important when the number of iterations per scenario is low. <span class="citation" data-cites="gilbert2024multilevel">Gilbert and Miratrix (<a href="references.html#ref-gilbert2024multilevel" role="doc-biblioref">2024</a>)</span> examine this point in greater detail.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script>
document.addEventListener("DOMContentLoaded", function() {
  // Create fixed toggle button
  const toggleBtn = document.createElement("button");
  toggleBtn.id = "fixed-sidebar-toggle";
  toggleBtn.title = "Toggle Sidebar";
  toggleBtn.setAttribute("aria-label", "Toggle Sidebar");

  // SVG Icons for Open vs Closed state
  const iconSidebarOpen = `
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
      <path d="M2 1a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H2zm0 1h3v12H2V2zm4 12V2h8v12H6z"/>
    </svg>`;
    
  const iconSidebarClosed = `
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
      <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
      <path d="M11 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H10.5a.5.5 0 0 1 .5.5z"/>
    </svg>`;

  toggleBtn.innerHTML = iconSidebarOpen;

  toggleBtn.addEventListener("click", function() {
    const isHidden = document.body.classList.toggle("sidebar-hidden");
    toggleBtn.innerHTML = isHidden ? iconSidebarClosed : iconSidebarOpen;
  });

  document.body.appendChild(toggleBtn);
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/jepusto\.github\.io\/Designing-Simulations-in-R\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./070-experimental-design.html" class="pagination-link" aria-label="Designing multifactor simulations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Designing multifactor simulations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./074-building-good-vizualizations.html" class="pagination-link" aria-label="Building good visualizations">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Building good visualizations</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/jepusto/Designing-Simulations-in-R/edit/main/072-presentation-of-results.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>