

# Simulations as evidence

We began this book with an acknowledgement that simulation is fraught with the potential for misuse: _simulations are doomed to succeed_.
We close by reiterating this point, and then discuss several ways researchers might design their simulations so they more arguably produce real evidence on how well things might work.

When our work is done, ideally we will have generated simulations that provide a sort of "consumer product testing" for the study designs and statistical methods we are exploring.
Clearly, it is important to do some consumer product tests that are grounded in how consumers will actually use the product in real life---but before you get to that point, it can be helpful to cover an array of conditions that are probably more extreme than what will be experienced in practice (like dropping things off buildings or driving over them with cars or whatever else).
These extreme contexts give us more clear results, and can help us understand the limits of our methods.
These extreme contexts are also usually best-case (or at least optimistic) scenarios for when our estimator of interest will excel, giving in effect an upper bound on how well things could go.

Extreme and clear simulations are also usually easier to write, manipulate, and understand.
Such simulations can help us learn about the estimators themselves.
For example, simulation can help uncover how different aspects of a data generating process affect the performance of an estimator.
To discover this, you need a data generation process with clear levers controlling those aspects.
Simple simulations can be used to push theory further---we can experiment to gain an inclination of whether a model is a good idea at all, or to verify we are right about an intuition or derivation about how well an estimator can work.

But such simulations cannot be the end of our journey.
In general, a researcher should work to ensure their simulation evidence is _relevant_.
A set of simulations only using unreaslistic data generating processes may not be that useful.
Unless the estimators being tested have truly universally stable properties, we will not learn much from a simulation that is not relevant to the problem at hand.
We have to circle back to providing testing of the sorts of situations an eventual user of our methods might encounter in practice.
So how can we make our simulations more relevant?


## Strategies for making relevant simulations

In the following subsections we go through a range of general strategies for making relevant simulations:

 1.   Use extensive multi-factor simulations
 2.   Generate simulations based on prior literature.
 3.   Pick simulation factors based on real data
 4.   Resample real data directly to get authentic distributions
 5.   Design a fully calibrated simulation
 


### Make your simulation general with an extensive multi-factor experiment

"If a single simulation is not convincing, use more of them," is one principle a researcher might take.
By conducting extensive multifactor simulations, once can explore a large space of possible data generating scenarios.
If, across the full range of scenarios, a general story bears out, then perhaps that will be more convincing than a narrower range.

Of course, the critic will claim that some aspect that is not varying is the real culprit.
If this aspect is unrealistic, then the findings, across the board, may be less relevant.
Thus, pick the factors one varies with care.


### Use previously published simulations to beat them at their own game

If a relevant prior paper uses a simulation to make a case, one approach is to replicate that simulation, adding in the new estimator one wants to evaluate.
This makes it (more) clear that you are not fishing: you are using something established in the literature as a published benchmark.
By constraining oneself to published simulations, one has less wiggle room to cherry pick a data generating process that works the way you want.



### Calibrate simulation factors to real data

Use real data to inform choice of factor levels or other data generation features.
For example, in James's work on designing methods for meta-analysis, there is often a question of how big sample sizes should be and how many different outcomes per study there should be when simulating effect size estimates from hypothetical studies to be included in a hypothetical meta-analysis.
To make the simulations realistic, James obtained data from a set of past real meta-analyses and fit parametric models to these features, and used the resulting parameter estimates as benchmarks for how large and how varied the simulated meta analyses should be.

In this case, one would probably not use the exact estimated values, but instead use them as a point of reference and possibly explore a range of values around them.
For instance, say we find that the distribution of study sizes fits a Poisson(63) pretty well.
We might then then simulate study sizes using a Poisson with mean parameters of 40, 60, or 80 (where 40, 60, and 80 would be one factor in our multifactor experiment).


### Use real data to obtain directly

You can also use real data directly to avoid a parametric model.
For example, say you need a population distribution for a slew of covariates.
Rather than using something artificial (like multivariate normal), you can pull population data on a bunch of covariates from some administrative data and then use those data as a (finite) population distribution.
You then simple sample (possibly with replacement) rows from your reference population to generate your simulationsample.

The appeal here is that your covariates will then have distributions that are much more authentic than some multivariate normal--they will include both continuous and categorical variables, they will tend to be skewed, and they will be correlated in different ways that are more interesting than anything someone could make up.

As an illustration of this approach, an old paper on heteroscedasticity-robust standard errors (Long and Irvin, 2000)  does something similar.
It was important in the context that they’re studying because the behavior of heteroscedasticity-robust SEs is influenced by leverage, which is a function of the covariate distribution.
Getting authentic leverage was hard to do with a parametric model, so getting examples of it from real life made the simulation more relevant.


### Fully calibrated simulations

Extending some of the prior ideas even further, one practice in increasing vogue is to generate _calibrated simulations_.
These are simulations tailored to a specific applied contexts, where we design our simulation study to more narrowly inform what assumptions and structures are necessary in order to make progress in that specific context.

Often we would do this by building our simulations out of existing data.
For an example from above, one might sample, with replacement, from the covariate distribution of an actual dataset so that the distribution of covariates is authentic in how the covariates are distributed and, more importantly, how they co-relate.

But this is not far enough.
We also need to generate a realistic relationship between our covariates and outcome to truly assess how well the estimators work in practice.
It is very easy to accidentally put a very simple model in place for this final component, thus making a calibrated simulation quite naive in, perhaps, the very way that counts.

We next walk through how you might calibrate further in the context of evaluating estimators for some sort of causal inference context where we are assessing methods of estimating a treatment effect of some binary treatment.
If we just resample our covariates, but then layer a constant treatment effect on top, we may be missing critical aspects of how our estimators might fail in practice.

In the area of causal inference, the potential outcomes framework provides a natural path for generating calibrated simulations [@Kern_calibrated].
Also see \@ref(potential-outcomes) for more discussion of simulations in the potential outcomes framework.
Under this framework, we would take an existing randomized experiment or observational study and then impute all the missing potential outcomes under some specific scheme.
This fully defines the sample of interest and thus any target parameters, such as a measure of heterogeneity, are then fully known.
For our simulation we then synthetically, and repeatedly, randomize and ``observe'' outcomes to be analyzed with the methods we are testing.
We could also resample from our dataset to generate datasets of different size, or to have a superpopulation target as our estimand.

The key feature here is the imputation step: how do we build our full set of covariates and outcomes?
One baseline method one can use is to generate a matched-pairs dataset by, for each unit, finding a close match given all the demographic and other covariate information of the sample.  We then use the matched unit as the imputed potential outcome.  
By doing this (with replacement) for all units we can generate a fully imputed dataset which we then use as our population, with all outcomes being "real," as they are taken from actual data.
Such matching can preserve complex relationships in the data that are not model dependent.
In particular, if outcomes tend to be coarsely defined (e.g., on an integer scale) or have specific clumps (such as zero-inflation or rounding), this structure will be preserved.

One concern with this approach is the noise in the matching could in general dilute the structure of the treatment effect as the control- and treatment-side potential outcomes may be very unrelated, creating a lot of so-called idiosyncratic treatment variation (unit-to-unit variation in the treatment effects that is not explained by the covariates).
This is akin to measurement error diluting found relationships in linear models.
We could reduce such variation by first imputing missing outcomes using some model (e.g., a random forest) fit to the original data, and then matching on all units including the imputed potential outcome as a hidden "covariate."
This is not a data analysis strategy, but instead a method of generating synthetic data that both has a given structure of interest and also remains faithful to the idiosyncrasies of an actual dataset.

A second approach that allows for varying the level of a systematic effect is to specify a treatment effect model, predict treatment effects for all units and use those to impute the treatment potential outcome for all control units.
This will perfectly preserve the complex structure between the covariates and the $Y_i(0)$s.
Unfortunately, this would also give no idiosyncratic treatment variation .
To add in idiosyncratic variation we could then need to generate a distribution of perturbations and add these to the imputed outcomes just as an error term in a regression model.  

Regardless of how we generate them, once we have a "fully observed" sample with the full set of treatment and control potential outcomes for all of our units, we can calculate any target estimands we like on our population, and then compare our estimators to these ground truths (even if they have no parametric analog) as desired.

Clearly, these calibration games can be fairly complex.
They do not lend themselves to a clear factor-based structure that have levers that change targeted aspects of the data generating process (although sometimes you can build in controls to make such levers possible).
In exchange, we end up with a simulation that might be more faithfully capturing aspects of a specific context, making our simulations more relevant to answering the narrower question of "how will things work here?"

