project:
  type: book
  output-dir: _book

book:
  title: "Designing Monte Carlo Simulations in R"
  author:
    - name: "Luke W. Miratrix"
    - name: "James E. Pustejovsky"
  date: today
  description: "A text on designing, implementing, and reporting on Monte Carlo simulation studies"
  repo-url: https://github.com/jepusto/Designing-Simulations-in-R
  repo-branch: main
  repo-actions: [edit]
  site-url: https://jepusto.github.io/Designing-Simulations-in-R/
  downloads: [pdf, epub]
  search: true

  chapters:
    - index.qmd

    - part: "An Introductory Look"
      chapters:
        - 001-introduction.qmd
        - 003-programming-preliminaries.qmd
        - 005-initial-t-test-simulation.qmd

    - part: "Structure and Mechanics of a Simulation Study"
      chapters:
        - 010-Simulation-structure.qmd
        - 015-Case-study-ANOVA.qmd
        - 020-Data-generating-models.qmd
        - 030-Estimation-procedures.qmd
        - 035-running-simulation.qmd
        - 040-Performance-criteria.qmd

    - part: "Systematic Simulations"
      chapters:
        - 060-multiple-scenarios.qmd
        - 070-experimental-design.qmd
        - 072-presentation-of-results.qmd
        - 074-building-good-vizualizations.qmd
        - 075-special-topics-on-reporting.qmd
        - 077-case-study-comparing-estimators.qmd
        - 080-simulations-as-evidence.qmd

    - part: "Computational Considerations"
      chapters:
        - 100-file-management.qmd
        - 110-debugging-and-testing.qmd
        - 120-parallel-processing.qmd

    - part: "Complex Data Structures"
      chapters:
        - 140-simulation-for-power-analysis.qmd
        - 150-potential-outcomes-framework.qmd
        - 160-parametric-bootstrap.qmd

  appendices:
    - 200-coding-tidbits.qmd
    - 210-further-resources.qmd

bibliography:
  - book.bib
  - packages.bib

format:
  html:
    theme: default
    css: css/style.css
    include-in-header: mathjax-preamble.html
    toc: true
    toc-depth: 3
    number-sections: true

  pdf:
    documentclass: krantz
    classoption: ["krantz1"]
    include-in-header: latex/preamble.tex
    include-after-body: latex/after_body.tex
    keep-tex: true
    cite-method: natbib
    biblio-style: apalike
    fig-format: pdf
    pdf-engine: xelatex
    top-level-division: chapter
    toc: true
    toc-depth: 3
    number-sections: true

  epub:
    css: css/style.css
    toc: true

knitr:
  opts_chunk:
    echo: true
    fig.width: 5
    fig.height: 3
    out.width: "75%"
    fig.align: center
    message: false
    warning: false
