book_filename: "Designing-Simulations-in-R"
title: "Designing Simulations in R"
author: "Luke W. Miratrix and James E. Pustejovsky (Equal authors)"
description: "How to design Monte Carlo simulations in R."
