--- 
title: "Designing Monte Carlo Simulations in R"
author: "Luke W. Miratrix and James E. Pustejovsky\n(Equal authors)"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: jepusto/Designing-Simulations-in-R
description: "A text on designing, implementing, and reporting on Monte Carlo simulation studies"
---

```{r echo = FALSE, messages = FALSE, warnings = FALSE, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE, 
                      fig.width = 5,
                      fig.height = 3,
                      out.width = "75%", 
                      fig.align = "center")
options(list(dplyr.summarise.inform = FALSE))
theme_set( theme_classic() )


# automatically create a bib database for R packages
# These pulled from a grep of the Rmd files in the book, and made into a list of unique packages.
# devtools::install_github("lmiratrix/blkvar")
packs = c("tidyverse", "dplyr", "ggplot2", "simhelpers", "psych", "mvtnorm", "lme4", "arm", "lmerTest", "estimatr", "blkvar", "microbenchmark", "purrr", "future", "furrr", "tidyr", "lsr", 'bookdown', 'simhelpers', 'knitr', 'rmarkdown', 'purrr')
pacman::p_load( char = packs )

knitr::write_bib(
  packs,
  'packages.bib'
)


```

# Welcome {-}

Monte Carlo simulations are a computational technique for investigating the performance of a statistical model or method under known data-generating processes.
By controlling the data generating process (e.g., by specifying true values for the parameters of a statistical model) and then repeatedly applying a statistical method to data generated by that process, it becomes possible to assess how well a statistical method works. Monte Carlo simulations are an essential tool of inquiry for quantitative methodologists and students of statistics, useful both for small-scale or informal investigations and for formal methodological research.
In this monograph, we aim to provide an introduction to the logic and mechanics of designing simulation studies, using the R programming language. Our focus is on simulation studies for formal research purposes, as might appear in a methodological journal article, and for informing the design of empirical studies (e.g., power analysis).

## License {-}

This book is licensed to you under [Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License](http://creativecommons.org/licenses/by-nc-nd/4.0/).

The code samples in this book are licensed under [Creative Commons CC0 1.0 Universal (CC0 1.0)](https://creativecommons.org/publicdomain/zero/1.0/), i.e. public domain.


# About the authors {-}


James E. Pustejovsky is an associate professor at the University of Wisconsin - Madison, where he teaches in the Quantitative Methods Program within the Department of Educational Psychology. He completed a Ph.D. in Statistics at Northwestern University.

*Luke Miratrix*: I am currently an associate professor at Harvard University's Graduate School of Education. I completed a Ph.D. in Statistics at UC Berkeley after having traveled through three different graduate programs (computer science at MIT, education at UC Berkeley, and then finally statistics at UC Berkeley). Simulation has become a way for me to think, over the years. This might be because I am fundamentally lazy, and the idea of sitting down and trying to do a bunch of math to figure something out seems less fun than writing up some code "real quick" so I can see how things operate. Of course, "real quick" rarely is that quick – and before I know it I got sucked into trying to learn some esoteric aspect of how to best program something, and then a few rabbit holes later I may have discovered something interesting!  I find simulation quite absorbing, and I also find them reassuring (usually with regards to whether I have correctly implemented some statistical method). This book has been a real pleasure to write, because it's given me actual license to sit down and think about why I do the various things I do, and also which way I actually prefer to approach a problem. And getting to write this book with my co-author has been a particular pleasure, for talking about the business of writing simulations is rarely done in practice. This has been a real gift, and I have learned so much.



# Acknowledgements {-}

The material in this book was initially developed through courses that we offered at the University of Texas at Austin (James) and Harvard University (Luke) as well as from a series of workshops that we offered through the Society for Research on Educational Effectiveness in June of 2021. We are grateful for feedback, questions, and corrections we have received from many students who participated in these courses.  Some parts of this book are based on memos or other writings generated for various purposes,  some of which were written by others. This is been attributed throughout.
