
# Script to run the power code as a separate file.
# Generated by old knitr::purl() from that chapter.


library(tidyverse)
conflicted::conflicts_prefer(dplyr::select)
conflicted::conflicts_prefer(dplyr::filter)

knitr::opts_chunk$set(echo = TRUE, 
                      fig.width = 5,
                      fig.height = 3,
                      out.width = "75%", 
                      fig.align = "center")
options(list(dplyr.summarise.inform = FALSE))
theme_set( theme_classic() )

set.seed( 4404041 )
library(future)
library(furrr)



## ----messages=FALSE, warnings=FALSE, include=FALSE-----------------------------------------------------------
datW = read_csv( "data/discipline_data.csv" )
datW[,2:6] = round( exp( datW[,2:6] ), digits = 3 )


## ------------------------------------------------------------------------------------------------------------
print( datW, n=4 )


## ------------------------------------------------------------------------------------------------------------
datWl = log( datW[ , -1] )
lpd_mns = apply( datWl, 2, mean )
lpd_mns

lpd_cov = cov( datWl )
round( lpd_cov, digits=2 )


## ------------------------------------------------------------------------------------------------------------
make_dat_param = function( n_c, n_t, tx=1 ) {
  n = n_c + n_t
  lpdisc = MASS::mvrnorm( n, mu = lpd_mns, Sigma = lpd_cov )
  lpdisc = exp( lpdisc )
  colnames( lpdisc ) = paste0( "pdisc_", colnames( lpdisc ) )
  lpdisc = dplyr::as_tibble( lpdisc ) %>%
    dplyr::mutate( ID = 1:(dplyr::n()),
                   Z = 0 + ( sample( n ) <= n_t ) )
  
  # Add in treatment effect
  lpdisc = dplyr::mutate( lpdisc, 
                          pdisc_2018 = pdisc_2018 * ifelse( Z == 1, tx, 1 ),
                          pdisc_2019 = pdisc_2019 * ifelse( Z == 1, tx, 1 ) )
  
  lpdisc %>% 
    dplyr::relocate( ID, Z )
}


## ------------------------------------------------------------------------------------------------------------
set.seed( 594585 )
a = make_dat_param( 100, 100, 0.5 )  
print( a, n = 4 )


## ----echo=FALSE----------------------------------------------------------------------------------------------
datWL <- datW %>% 
  pivot_longer( `2015`:`2019`, names_to = "year",
                values_to = "pdisc" ) %>%
  mutate( year = as.numeric( year ) ) %>%
  group_by( year ) %>%
  summarise( pdisc = mean( pdisc ) )

aL = a %>% 
  pivot_longer( pdisc_2015:pdisc_2019, 
                names_to = c( ".value", "year" ),
                names_pattern = "(.*)_(.*)" ) %>%
  mutate( year = as.numeric( year ) )

aLg = aL %>% group_by( year, Z ) %>%
  summarise( pdisc = mean( pdisc ) )

ggplot( aLg, aes( year, pdisc, col=as.factor(Z) ) ) +
  geom_line() + geom_point() +
  scale_color_manual( values = c("orange","blue", "black" ) ) +
  geom_line( data=datWL, aes( x=year, y=pdisc, col="Real Data" ), lty=2 ) +
  labs( title = "Synthetic discipline data compared to initial data",
        color = "Tx Grp" )


## ------------------------------------------------------------------------------------------------------------
eval_dat = function( sdat ) {
  
  # No covariate adjustment, average change model (on log outcome)
  M_raw = lm( log( pdisc_2018 ) ~ 1 + Z, data=sdat )
  
  # Simple average change model using 2018 as outcome.
  M_simple = lm( pdisc_2018 ~ 1 + Z + pdisc_2017 + pdisc_2016 + pdisc_2015,
                 data=sdat )
  
  # Simple model on logged outcome
  M_log = lm( log( pdisc_2018 ) ~ 1 + Z + log( pdisc_2017) + 
                log( pdisc_2016) + log( pdisc_2015 ),
              data=sdat )
  
  # Ratio of average disc to average prior disc as outcome
  sdat = dplyr::mutate( sdat,
                        avg_disc = (pdisc_2018 + pdisc_2019)/2,
                        prior_disc = (pdisc_2017 + pdisc_2016 + pdisc_2015 )/3,
                        disc = pdisc_2018 / prior_disc,
                        disc_two = avg_disc / prior_disc )
  M_ratio = lm( disc ~ 1 + Z, data = sdat )
  M_ratio_twopost = lm( disc_two ~ 1 + Z, data = sdat )
  
  # Use average of two post-tx time periods, averaged to reduce noise
  M_twopost = lm( log( avg_disc ) ~ 1 + Z + log( pdisc_2017 ) + 
                    log( pdisc_2016 ) + log( pdisc_2015 ), 
                  data=sdat )
  
  # Time and unit fixed effects
  sdatL = tidyr::pivot_longer( sdat, cols = pdisc_2015:pdisc_2019, 
                               names_to = "year",
                               values_to = "pdisc" ) %>%
    dplyr::mutate( Z = Z * (year %in% c( "pdisc_2018", "pdisc_2019" ) ),
                   ID = paste0( "S", ID ) )
  
  M_2wfe = lm( log( pdisc ) ~ 0 + ID + year + Z,
               data=sdatL )
  
  # Bundle all our models by getting the estimated treatment impact
  # from each.
  models <- list( raw=M_raw, simple=M_simple,
                  log=M_log, ratio = M_ratio, 
                  ratio_twopost = M_ratio_twopost,
                  log_twopost = M_twopost, 
                  FE = M_2wfe )
  rs <- purrr::map_df( models, broom::tidy, .id="model" ) %>%
    dplyr::filter( term=="Z" ) %>%
    dplyr::select( -term ) %>%
    dplyr::arrange( model )
  
  rs
}


## ------------------------------------------------------------------------------------------------------------
dat = make_dat_param( n_c = 4, n_t = 4, tx = 0.5 )
eval_dat( dat )


## ------------------------------------------------------------------------------------------------------------
sim_run = simhelpers::bundle_sim( make_dat_param, eval_dat )


## ------------------------------------------------------------------------------------------------------------
res = expand_grid( tx = c( 1, 0.75, 0.5 ),
                   n_c = c( 4, 5, 6, 8, 12, 20 ),
                   n_t = c( 4, 5, 6 ) )
res$reps = 1000
res$seed = 1010203 + 1:nrow(res)


## ----secret_run_disc_simulation, include=FALSE---------------------------------------------------------------
if ( FALSE ) {
  sim_run( 4, n_c = 20, n_t = 5 )
}

library( future )
library( furrr )
plan(multisession, workers = parallel::detectCores() - 1 )

#res$reps = 10

fopts = furrr_options(seed = NULL,
                      globals = c("lpd_mns", "lpd_cov") )
res_u <- simhelpers::evaluate_by_row( params = res,
                                      sim_run, 
                                      .options = fopts,                 
                                      .progress = TRUE )

plan( sequential )

res_u

saveRDS( res_u, file="data/discipline_simulation.rds" )
